## This file contain
* Create Matrices
* Create Matrices with default Values
 * Zeros
 * Ones
* Seed with cpu and Gpu
* Convert Numpy to Torch , Torch to numpy
* Move Tensor Cpu to Gpu
* Tensor operation
    * Element wise add, sub, mul div
    * Resize
    * Calculate mean
    * Calculate STD

## Creating Matrices 

In [1]:
import numpy as np
import torch
import sys

In [2]:
# creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# convert to numpy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
# convert to torch
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

## Create Matrices with Default Values

In [5]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
torch.ones((2, 2))

tensor([[1., 1.],
        [1., 1.]])

In [7]:
np.random.rand(2, 2)

array([[0.33693558, 0.68172709],
       [0.23231241, 0.82094871]])

In [8]:
torch.rand(2, 2)

tensor([[0.8832, 0.2404],
        [0.2686, 0.1683]])

## Seed for Reproducibility 

In [12]:
# seed
np.random.seed(0)
np.random.rand(2, 2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [14]:
# no seed
np.random.rand(2,2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [15]:
# torch seed
torch.manual_seed(0)
torch.rand(2, 2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [17]:
torch.rand(2, 2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

In [18]:
# seed fo gpu
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

## Numpy to Torch Bridge 

In [19]:
np_arr = np.ones((2, 2))
print(np_arr)
type(np_arr)

[[1. 1.]
 [1. 1.]]


numpy.ndarray

In [20]:
# converting to torch
torch_tensor = torch.from_numpy(np_arr)
print(torch_tensor)
type(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


torch.Tensor

In [21]:
# torch to numpy
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

In [23]:
np_array_new=np.ones((2,2),dtype=np.int8)
np_array_new

array([[1, 1],
       [1, 1]], dtype=int8)

In [24]:
#data type matter
torch.from_numpy(np_array_new)

TypeError: can't convert np.ndarray of type numpy.int8. The only supported types are: double, float, float16, int64, int32, and uint8.

# The conversion supports:

1-double<br>
2-float<br>
3-int64 , int32, uint8


In [29]:
np_array_new=np.ones((2,2),dtype=np.int64)
taraay=torch.from_numpy(np_array_new)
print(taraay)


tensor([[1, 1],
        [1, 1]])


In [32]:
# Torach to Numpy

torch_tensor= torch.ones(2,2)
torch_tensor.type

<function Tensor.type>

In [36]:
torch_to_numpy=torch_tensor.numpy()
torch_to_numpy

array([[1., 1.],
       [1., 1.]], dtype=float32)

## Torch cpu to gpu to cpu

In [17]:
# check cuda is available
torch.cuda.is_available()

True

In [18]:
# clear all variable to clear ram 
# sys.modules[__name__].__dict__.clear()

In [19]:
# cpu
tensor_cpu = torch.ones(2, 2)

In [20]:
# Cpu to Gpu
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [21]:
tensor_cpu.cuda()
# Gpu to Cpu
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

## Tensor Operatoins

In [22]:
a = torch.ones(2, 2)
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [23]:
a.size()

torch.Size([2, 2])

In [24]:
# convert vactor
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [37]:
a.view(4).size()

RuntimeError: shape '[4]' is invalid for input of size 1

### Add

In [25]:
b = a + a
b


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [26]:
b = torch.add(a, a)
b


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [27]:
# in place addition 
print('Old B', b)

b.add_(a)
print('_'*60)
print()
print('New B', b)

Old B 
 2  2
 2  2
[torch.FloatTensor of size 2x2]

____________________________________________________________

New B 
 3  3
 3  3
[torch.FloatTensor of size 2x2]



### sub

In [28]:
a - a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [29]:
a.sub(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [30]:
a


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [31]:
a.sub_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [32]:
a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

### mul

In [33]:
a = torch.ones(2,2)
b = torch.Tensor([[2,2],[2,2]])

In [34]:
a * b


 2  2
 2  2
[torch.FloatTensor of size 2x2]

In [35]:
print('Old')
print(a.mul(b))
print(a)
print('_'*60)
print('New')
print(a.mul_(b))
print(a)

Old

 2  2
 2  2
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]

____________________________________________________________
New

 2  2
 2  2
[torch.FloatTensor of size 2x2]


 2  2
 2  2
[torch.FloatTensor of size 2x2]



## Div

In [36]:
a = torch.ones(2,2)
b = torch.Tensor([[2,2],[2,2]])

In [37]:
a / b


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [38]:
torch.div(a,b)


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [39]:
a.div(b)


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [40]:
a.div_(b)


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

In [41]:
a


 0.5000  0.5000
 0.5000  0.5000
[torch.FloatTensor of size 2x2]

## Tensor Mean

In [42]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.size()

torch.Size([10])

In [43]:
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [44]:
a = torch.Tensor([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a.size()

torch.Size([2, 10])

In [45]:
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

## Tensor STD

In [46]:
a = torch.Tensor([1,2,3,4,5,6,7,8,9,10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]